with open('nicegui_screens/certificate_screen.py', 'r', encoding='utf-8') as f:
    content = f.read()

import re

lines = [
    "    # Set to True to enable verbose printing of docxtpl context variables in the terminal/log",
    "    ENABLE_CONTEXT_LOGGING: bool = False",
    "",
    "    @staticmethod",
    "    def print_certificate_context(ctx: dict, enabled: bool = False) -> None:",
    '        """',
    "        Prints every variable passed to Word (docxtpl) line by line to standard output (terminal)",
    "        and system logs so the user can track every data field step by step.",
    "        Set `ENABLE_CONTEXT_LOGGING = True` or pass `enabled=True` to activate in the future.",
    '        """',
    "        if not (enabled or CertificateScreen.ENABLE_CONTEXT_LOGGING):",
    "            return",
    "",
    '        banner = "=" * 80',
    "        log_lines = [",
    '            "",',
    "            banner,",
    '            "  === WORD DOCXTPL CONTEXT VARIABLES TRACKING LOG ===",',
    "            banner,",
    '            r"\\n--- [1. TOP-LEVEL SCALAR VARIABLES & METADATA] ---",',
    "        ]",
    "",
    "        scalars = {}",
    "        lists_and_dicts = {}",
    "        for k, v in ctx.items():",
    "            if isinstance(v, (list, dict)):",
    "                lists_and_dicts[k] = v",
    "            else:",
    "                scalars[k] = v",
    '                log_lines.append(f"  • {k:<30} = {repr(v)}")',
    "",
    "        # Signatories",
    '        signatories = ctx.get("signatories")',
    "        if isinstance(signatories, list):",
    '            log_lines.append(f"\\n--- [2. SIGNATORIES ({len(signatories)} Total)] ---")',
    "            for idx, sig in enumerate(signatories):",
    "                if isinstance(sig, dict):",
    "                    log_lines.append(",
    '                        f"  ► Signatory {idx+1}: name=\'{sig.get(\'name\')}\', title=\'{sig.get(\'title\')}\', order={sig.get(\'order\')}"',
    "                    )",
    "                else:",
    '                    log_lines.append(f"  ► Signatory {idx+1}: {sig}")',
    "",
    "        # Tables & Paired Semesters / Years",
    "        printed_table_ids = set()",
    '        for table_key in ("paired_semesters", "paired_years", "semesters"):',
    "            table_list = ctx.get(table_key)",
    "            if isinstance(table_list, list) and table_list:",
    "                if id(table_list) in printed_table_ids:",
    '                    log_lines.append(f"\\n--- [3. TABLE DATA: \'{table_key}\' (Same data as paired_semesters — skipped duplicate print)] ---")',
    "                    continue",
    "                printed_table_ids.add(id(table_list))",
    '                log_lines.append(f"\\n--- [3. TABLE DATA: \'{table_key}\' ({len(table_list)} Tables/Rows)] ---")',
    "                for t_idx, table_item in enumerate(table_list):",
    '                    log_lines.append(r"\\n  ==========================================================================")',
    "                    log_lines.append(f\"  ► Table {t_idx+1}:\")",
    '                    log_lines.append(f"      left_label       : \'{table_item.get(\'left_label\', \'\')}\'")',
    '                    log_lines.append(f"      right_label      : \'{table_item.get(\'right_label\', \'\')}\'")',
    '                    log_lines.append(f"      year_left_label  : \'{table_item.get(\'year_left_label\', \'\')}\'")',
    '                    log_lines.append(f"      year_right_label : \'{table_item.get(\'year_right_label\', \'\')}\'")',
    '                    log_lines.append(f"      year_label       : \'{table_item.get(\'year_label\', \'\')}\'")',
    '                    log_lines.append(f"      academic_year    : \'{table_item.get(\'academic_year\', \'\')}\'")',
    '                    log_lines.append(f"      num_s_l          : \'{table_item.get(\'num_s_l\', \'\')}\'")',
    '                    log_lines.append(f"      num_s_r          : \'{table_item.get(\'num_s_r\', \'\')}\'")',
    '                    log_lines.append(f"      year_s_l         : \'{table_item.get(\'year_s_l\', \'\')}\'")',
    '                    log_lines.append(f"      year_s_r         : \'{table_item.get(\'year_s_r\', \'\')}\'")',
    '                    log_lines.append(f"      stage_s_l        : \'{table_item.get(\'stage_s_l\', \'\')}\'")',
    '                    log_lines.append(f"      stage_s_r        : \'{table_item.get(\'stage_s_r\', \'\')}\'")',
    '                    log_lines.append(f"      stage_text       : \'{table_item.get(\'stage_text\', \'\')}\'")',
    "",
    '                    rows = table_item.get("rows", [])',
    "                    if isinstance(rows, list) and rows:",
    '                        log_lines.append(f"\\n      --- Courses ({len(rows)} Rows) ---")',
    '                        log_lines.append(f"      {\\'#\\':<3} | {\\'RIGHT SUBJECT\\':<35} | {\\'MARK\\':<6} | {\\'UNIT\\':<5} || {\\'LEFT SUBJECT\\':<35} | {\\'MARK\\':<6} | {\\'UNIT\\':<5}")',
    '                        log_lines.append("      " + "-" * 105)',
    "                        for r_idx, r in enumerate(rows):",
    "                            if isinstance(r, dict):",
    '                                r_subj = str(r.get(\'right_name\') or r.get(\'right_subj\') or \'\')',
    '                                r_mark = str(r.get(\'right_mark\') or \'\')',
    '                                r_unit = str(r.get(\'right_unit\') or \'\')',
    '                                l_subj = str(r.get(\'left_name\') or r.get(\'left_subj\') or \'\')',
    '                                l_mark = str(r.get(\'left_mark\') or \'\')',
    '                                l_unit = str(r.get(\'left_unit\') or \'\')',
    "                                log_lines.append(",
    '                                    f"      {r_idx+1:<3} | {r_subj:<35} | {r_mark:<6} | {r_unit:<5} || {l_subj:<35} | {l_mark:<6} | {l_unit:<5}"',
    "                                )",
    "",
    "        log_lines.append(banner)",
    '        full_output = "\\n".join(log_lines)',
    "",
    "        print(full_output, flush=True)",
    "        log.info(full_output)",
]

replacement = "\n".join(lines)

pattern = r'# Set to True to enable verbose printing of docxtpl context variables in the terminal/log\s*ENABLE_CONTEXT_LOGGING: bool = False\s+@staticmethod\s+def print_certificate_context\(ctx: dict, enabled: bool = False\) -> None:.*?(?=    def generate_docx)'

content = re.sub(pattern, replacement + "\n\n", content, flags=re.DOTALL)

with open('nicegui_screens/certificate_screen.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated certificate_screen.py with r-strings.")
